webtalk_init -webtalk_dir /home/issam/FPGA/tempmux/TEMPMUX/TEMPMUX.sim/sim_1/behav/xsim/xsim.dir/T_TEMPMUX_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Aug  5 15:01:55 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f7250829-a131-4831-86de-2bf78ea4deb8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0bad000ccfae4fc1814cadbc523d4b55" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "25" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 24.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-1250U" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2864.152 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "270 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114872_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2640105392 -regid "" -xml /home/issam/FPGA/tempmux/TEMPMUX/TEMPMUX.sim/sim_1/behav/xsim/xsim.dir/T_TEMPMUX_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/issam/FPGA/tempmux/TEMPMUX/TEMPMUX.sim/sim_1/behav/xsim/xsim.dir/T_TEMPMUX_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/issam/FPGA/tempmux/TEMPMUX/TEMPMUX.sim/sim_1/behav/xsim/xsim.dir/T_TEMPMUX_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
