#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Aug 04 17:09:46 CEST 2025
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 0bad000ccfae4fc1814cadbc523d4b55 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot T_TEMPMUX_tb_behav xil_defaultlib.T_TEMPMUX_tb -log elaborate.log"
xelab -wto 0bad000ccfae4fc1814cadbc523d4b55 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot T_TEMPMUX_tb_behav xil_defaultlib.T_TEMPMUX_tb -log elaborate.log

