#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Aug 04 17:09:47 CEST 2025
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim T_TEMPMUX_tb_behav -key {Behavioral:sim_1:Functional:T_TEMPMUX_tb} -tclbatch T_TEMPMUX_tb.tcl -log simulate.log"
xsim T_TEMPMUX_tb_behav -key {Behavioral:sim_1:Functional:T_TEMPMUX_tb} -tclbatch T_TEMPMUX_tb.tcl -log simulate.log

